version: '3.8'
services:
  app:
    build: .
    env_file: .env
    volumes:
      - ./data:/app/data
      - ./chroma_data:/app/chroma_data
    depends_on:
      - ollama
    gpus: all

  ollama:
    image: ollama/ollama:latest
    volumes:
      - ./ollama_models:/root/.ollama/models
    gpus: all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
