version: '3.8'

services:
  munirag:
    build: .
    container_name: munirag
    ports:
      - "8501:8501"
    env_file: .env
    volumes:
      - ./data:/app/data
      - ./chroma_data:/app/chroma_data
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ./ollama_models:/root/.ollama/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
